import { useEffect, useState } from "react";
import { ArrowRight, Download, FileCheck2, FilePlus2, RefreshCcw, Send, Trash2 } from "lucide-react";
import { apiClient } from "../api/client";
import type { Client, Lead } from "../types/crm";
import type { CommercialDashboard, CommercialDocument, CommercialItem, CommercialType } from "../types/commercial";

const tabs: Array<{ key: CommercialType; label: string }> = [{ key: "proposals", label: "Proposals" }, { key: "quotations", label: "Quotations" }, { key: "contracts", label: "Contracts" }];
const input = "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-semibold outline-none focus:border-emerald-500 focus:bg-white";
const money = (value: number) => `Rs. ${Number(value || 0).toLocaleString("en-IN")}`;

export default function CommercialPage() {
  const [active, setActive] = useState<CommercialType>("proposals"); const [documents, setDocuments] = useState<CommercialDocument[]>([]); const [clients, setClients] = useState<Client[]>([]); const [leads, setLeads] = useState<Lead[]>([]); const [dashboard, setDashboard] = useState<CommercialDashboard | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ title: "Digital Growth Engagement", target: "", validUntil: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10), scope: "Strategy, campaign setup, creative production, optimization and monthly reporting.", terms: "50% advance. Balance payable against agreed milestones.", taxPercent: 18, discountAmount: 0 });
  const [items, setItems] = useState<CommercialItem[]>([{ description: "Strategy and setup", quantity: 1, unitPrice: 25000 }, { description: "Monthly execution", quantity: 3, unitPrice: 30000 }]);

  async function load(type = active) { setBusy(true); try { const [d, docs, c, l] = await Promise.all([apiClient.get("/commercial/dashboard"), apiClient.get(`/commercial/${type}`), apiClient.get("/crm/clients"), apiClient.get("/crm/leads")]); setDashboard(d.data.data); setDocuments(docs.data.data || []); setClients(c.data.data || []); setLeads(l.data.data || []); const first = c.data.data?.[0]?.id ? `client:${c.data.data[0].id}` : l.data.data?.[0]?.id ? `lead:${l.data.data[0].id}` : ""; setForm(current => ({ ...current, target: current.target || first })); } catch { setMessage("Could not load commercial documents"); } finally { setBusy(false); } }
  useEffect(() => { void load(active); }, [active]);
  async function create() { if (!form.target) return setMessage("Create a CRM client or lead first"); setBusy(true); const [kind, id] = form.target.split(":"); try { await apiClient.post(`/commercial/${active}`, { ...form, clientId: kind === "client" ? id : null, leadId: kind === "lead" ? id : null, items }); setMessage(`${active.slice(0, -1)} created successfully`); await load(active); } catch { setMessage("Unable to create document. Check the form values."); } finally { setBusy(false); } }
  async function action(id: string, name: "send" | "convert") { setBusy(true); try { const response = await apiClient.post(`/commercial/${active}/${id}/${name}`); setMessage(name === "send" ? `Approval link: ${response.data.data.acceptanceUrl}` : "Next document generated successfully"); await load(active); } finally { setBusy(false); } }
  async function remove(id: string) { await apiClient.delete(`/commercial/${active}/${id}`); await load(active); }
  async function download(id: string, filename: string) { const response = await apiClient.get(`/commercial/${active}/${id}/pdf`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${filename}.pdf`; anchor.click(); URL.revokeObjectURL(url); }
  function updateItem(index: number, field: keyof CommercialItem, value: string) { setItems(current => current.map((item, i) => i === index ? { ...item, [field]: field === "description" ? value : Number(value) } : item)); }

  return <div className="space-y-6">
    <section className="rounded-[2rem] bg-gradient-to-br from-emerald-700 via-teal-800 to-slate-950 p-8 text-white"><p className="text-xs font-black uppercase tracking-[.28em] text-emerald-200">Phase 7</p><div className="mt-3 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 className="text-4xl font-black">Commercial Documents</h1><p className="mt-2 text-sm text-emerald-100">Build, price, export and collect client approval for proposals, quotations and contracts.</p></div><button onClick={() => load()} className="flex items-center gap-2 rounded-xl bg-white/10 px-4 py-3 text-sm font-black"><RefreshCcw size={17}/> Refresh</button></div></section>
    {message && <div className="break-all rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{message}</div>}
    <section className="grid gap-4 md:grid-cols-5">{[["Total",dashboard?.total],["Drafts",dashboard?.draft],["Awaiting",dashboard?.sent],["Accepted",dashboard?.accepted],["Accepted value",money(dashboard?.acceptedValue || 0)]].map(([label,value]) => <div key={String(label)} className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-slate-400">{label}</p><p className="mt-2 text-2xl font-black text-slate-950">{value ?? 0}</p></div>)}</section>
    <div className="flex gap-2 rounded-2xl border bg-white p-2">{tabs.map(tab => <button key={tab.key} onClick={() => setActive(tab.key)} className={`flex-1 rounded-xl px-4 py-3 text-sm font-black ${active === tab.key ? "bg-emerald-700 text-white" : "text-slate-500"}`}>{tab.label}</button>)}</div>
    <section className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]">
      <div className="rounded-2xl border bg-white p-6"><div className="flex items-center gap-2"><FilePlus2 className="text-emerald-700"/><h2 className="text-xl font-black">New {active.slice(0,-1)}</h2></div><div className="mt-5 space-y-3"><input className={input} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Document title"/><select className={input} value={form.target} onChange={e=>setForm({...form,target:e.target.value})}><option value="">Select client or lead</option>{clients.map(c=><option key={c.id} value={`client:${c.id}`}>Client - {c.name}</option>)}{leads.map(l=><option key={l.id} value={`lead:${l.id}`}>Lead - {l.companyName}</option>)}</select><div className="grid grid-cols-2 gap-3"><input type="date" className={input} value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/><input type="number" className={input} value={form.taxPercent} onChange={e=>setForm({...form,taxPercent:Number(e.target.value)})} placeholder="Tax %"/></div><textarea className={input} value={form.scope} onChange={e=>setForm({...form,scope:e.target.value})} rows={3}/><textarea className={input} value={form.terms} onChange={e=>setForm({...form,terms:e.target.value})} rows={2}/>{items.map((item,index)=><div key={index} className="grid grid-cols-[1fr_70px_100px] gap-2"><input className={input} value={item.description} onChange={e=>updateItem(index,"description",e.target.value)}/><input className={input} type="number" value={item.quantity} onChange={e=>updateItem(index,"quantity",e.target.value)}/><input className={input} type="number" value={item.unitPrice} onChange={e=>updateItem(index,"unitPrice",e.target.value)}/></div>)}<button onClick={()=>setItems([...items,{description:"New service",quantity:1,unitPrice:0}])} className="text-sm font-black text-emerald-700">+ Add line item</button><button disabled={busy} onClick={create} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-black text-white"><FileCheck2 size={18}/>Create {active.slice(0,-1)}</button></div></div>
      <div className="space-y-3">{documents.length === 0 && <div className="rounded-2xl border bg-white p-8 text-center font-bold text-slate-400">No {active} yet.</div>}{documents.map(doc=><article key={doc.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex items-center gap-2"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">{doc.status}</span><span className="text-xs font-bold text-slate-400">{doc.documentNumber}</span></div><h3 className="mt-3 text-lg font-black">{doc.title}</h3><p className="mt-1 text-sm font-semibold text-slate-500">{doc.client?.name || doc.lead?.companyName} - {money(doc.totalAmount)}</p></div><div className="flex flex-wrap items-center gap-2"><button title="PDF" onClick={()=>download(doc.id,doc.documentNumber)} className="rounded-xl border p-2.5"><Download size={17}/></button>{doc.status === "DRAFT" && <><button title="Send" onClick={()=>action(doc.id,"send")} className="rounded-xl bg-emerald-700 p-2.5 text-white"><Send size={17}/></button><button title="Delete" onClick={()=>remove(doc.id)} className="rounded-xl border p-2.5 text-red-600"><Trash2 size={17}/></button></>}{doc.type !== "CONTRACT" && <button onClick={()=>action(doc.id,"convert")} className="flex items-center gap-1 rounded-xl border px-3 py-2 text-xs font-black">Convert <ArrowRight size={14}/></button>}</div></div></article>)}</div>
    </section>
  </div>;
}
